version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    container_name: movies_notifications_db
    environment:
      - TZ=Europe/Moscow
    restart: always
    volumes:
      - /volume2/docker/movies_notifications/database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  parser:
    image: evgenferrum/movies_notifications:latest
    container_name: movies_notifications_parser
    environment:
      - TZ=Europe/Moscow
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
